# dein lazy

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'

[[plugins]]
repo = 'Shougo/vimshell.vim'
on_map = {n = '<Plug>'}
on_if = "!has('nvim')"
hook_add = 'nmap [Space]s  <Plug>(vimshell_switch)'

# コード補完
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_if = "!has('nvim')"
on_ft = 'python'
hook_source = '''
  let g:jedi#completions_enabled = 0
  let g:jedi#auto_vim_configuration = 0
  let g:jedi#smart_auto_mappings = 0
  let g:jedi#show_call_signatures = 0
'''

[[plugins]]
repo = 'marcus/rsense'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_source = '''
  " [VimでGoの開発環境を設定する方法のまとめ \- Qiita](http://qiita.com/koara-local/items/6c886eccfb459159c431)
  let g:go_highlight_functions = 1
  let g:go_highlight_methods = 1
  let g:go_highlight_structs = 1
  autocmd FileType go :highlight goErr cterm=bold ctermfg=214
  autocmd FileType go :match goErr /\<err\>/
'''

 [[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'context_filetype.vim'
on_if = "has('lua')"
on_event = 'InsertEnter'
hook_source = '''
  let g:neocomplete#enable_at_startup = 1
  source ~/.vim/rc/plugins/neocomplete.rc.vim
'''
