[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
# ディレクトリからファイルを選択
# http://qiita.com/0829/items/261225a51439776b36bf
repo = 'Shougo/vimfiler.vim'
hook_add= '''
  let g:vimfiler_as_default_explorer = 1
	" 別ウィンドウで開く
	nnoremap <space>fe :VimFilerExplore -split -winwidth=30 -find -no-quit<Cr>
	" 現在のファイルのディレクトリで開く
	nnoremap <space>ff :VimFilerBufferDir<Cr>
	" プロジェクトホームで開く
	nnoremap <space>fg :VimFiler -project<Cr>

  " Two columns of indentation.
  let g:vimfiler_tree_indentation = 2
'''
# ファイルをtree表示してくれる
# [[plugins]]
# repo = 'scrooloose/nerdtree'

# toml
[[plugins]]
repo = 'cespare/vim-toml'

# Gitを便利に使う
[[plugins]]
repo = 'tpope/vim-fugitive'

# シングルクオートとダブルクオートの入れ替え等
# cs"'みたいな
[[plugins]]
repo = 'tpope/vim-surround'

# vim-commentary gcでコメントアウト
[[plugins]]
repo = 'tpope/vim-commentary'

# 静的解析
[[plugins]]
repo = 'scrooloose/syntastic'
hook_add='''
  " You shouldn't use 'tsc' checker.
  let g:syntastic_typescript_checkers = ['tsuquyomi']
'''


# ドキュメント参照
[[plugins]]
repo = 'thinca/vim-ref'
[[plugins]]
repo = 'yuku-t/vim-ref-ri'

# メソッドの定義元へジャンプ
[[plugins]]
repo = 'szw/vim-tags'
# クラスのアウトラインを表示
[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
  nmap <C-r> :TagbarToggle<CR>
'''

# コメントON/OFFを手軽に実行
# [[plugins]]
# repo = 'tomtom/tcomment_vim'
# インデントに色を付けて見やすくする
# [[plugins]]
# repo = 'nathanaelkane/vim-indent-guides'
# ログファイルを色づけしてくれる
[[plugins]]
repo = 'vim-scripts/AnsiEsc.vim'
# 行末の半角スペースを可視化(うまく動かない？)
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# Markdown用
# 参考:http://www.key-p.com/blog/staff/archives/9032
# :PrevimOpen ブラウザでプレビューを表示する
[[plugins]]
repo = 'plasticboy/vim-markdown'
hook_add= '''
  let g:vim_markdown_folding_disabled = 1
'''
[[plugins]]
repo = 'kannokanno/previm'

# [Vim \- URL からブラウザオープン！ \- mk\-mode BLOG](http://www.mk-mode.com/octopress/2014/11/13/vim-open-browser-plugin/)
# gx でカーソル下のURLをブラウザでOPENする
[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
  let g:netrw_nogx = 1 " disable netrw's gx mapping.
  nmap gx <Plug>(openbrowser-smart-search)
  vmap gx <Plug>(openbrowser-smart-search)
'''

# 色々なカラースキーム
[[plugins]]
repo = 'flazz/vim-colorschemes'
hook_add = '''
  " [dein\.vimによるプラグイン管理のマイベストプラクティス \- Qiita](http://qiita.com/kawaz/items/ee725f6214f91337b42b)
  " set background=dark
  " au MyAutoGrp VimEnter * nested colorscheme monokai
'''

# サブモードを作る
[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'nsf/gocode'
rtp = 'vim'

# vimからHTTP GETやPOSTができる
[[plugins]]
repo = 'mattn/webapi-vim'

# ステータスラインを良い感じにする
[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''

'''


# ウィンドウマネージャ
# [【Vim】タイル型ウィンドウマネージャでタブいらず \| blog\.remora\.cx](http://blog.remora.cx/2013/05/use-dwm-in-vim.html)
# [[plugins]]
# repo = 'spolu/dwm.vim'
# hook_add = """
#   let g:dwm_map_keys=0
# """

