# dein lazy

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/tabpagebuffer.vim'

[[plugins]]
repo = 'sorah/unite-ghq'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = ['neomru.vim', 'tabpagebuffer.vim', 'unite-ghq']

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
on_source = ['unite.vim', 'vimshell.vim']

[[plugins]]
repo = 'Shougo/vimshell.vim'
on_map = {n = '<Plug>'}
on_if = "!has('nvim')"
hook_add = 'nmap [Space]s  <Plug>(vimshell_switch)'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

# 言語
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_if = "!has('nvim')"
on_ft = 'python'
hook_source = '''
  let g:jedi#completions_enabled = 0
  let g:jedi#auto_vim_configuration = 0
  let g:jedi#smart_auto_mappings = 0
  let g:jedi#show_call_signatures = 0
'''

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_source = '''
  " [VimでGoの開発環境を設定する方法のまとめ \- Qiita](http://qiita.com/koara-local/items/6c886eccfb459159c431)
  let g:go_highlight_functions = 1
  let g:go_highlight_methods = 1
  let g:go_highlight_structs = 1
  autocmd FileType go :highlight goErr cterm=bold ctermfg=214
  autocmd FileType go :match goErr /\<err\>/
'''

 [[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'context_filetype.vim'
on_if = "has('lua')"
on_event = 'InsertEnter'
hook_source = '''
  let g:neocomplete#enable_at_startup = 1
  " source ~/.vim/rc/plugins/neocomplete.rc.vim
'''

# emmet関連 http://qiita.com/alpaca_taichou/items/056a4c42fe7a928973e6
# <C-Y>, (Ctrl-yの直後に,)でタグ展開
# 使い方:http://motw.mods.jp/Vim/emmet-vim.html
[[plugins]]
repo = 'mattn/emmet-vim'
on_i = 1
hook_add = '''
  let g:user_emmet_mode = 'iv'
  let g:user_emmet_leader_key = '<C-y>'
  let g:use_emmet_complete_tag = 1
  let g:user_emmet_settings = {
          \ 'lang' : 'ja',
          \ 'html' : {
          \   'filters' : 'html',
          \ },
          \ 'css' : {
          \   'filters' : 'fc',
          \ },
          \ 'php' : {
          \   'extends' : 'html',
          \   'filters' : 'html',
          \ },
          \}
  augroup EmmitVim
    autocmd!
    autocmd FileType * let g:user_emmet_settings.indentation = '               '[:&tabstop]
  augroup END
'''

# Rails向けのコマンドを提供する
[[plugins]]
repo = 'tpope/vim-rails'
on_i = 1
# JavaScriptシンタックス
[[plugins]]
repo = 'jelera/vim-javascript-syntax'
on_i = 1
# css3シンタックス
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_i = 1
# coffe scriptシンタックス
[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_i = 1
# less用のsyntaxハイライト
[[plugins]]
repo = 'KohPoll/vim-less'
on_i = 1

# 自動で閉じる
[[plugins]]
repo = 'tpope/vim-endwise'
on_i = 1
