[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
# ディレクトリからファイルを選択
# http://qiita.com/0829/items/261225a51439776b36bf
repo = 'Shougo/vimfiler.vim'
hook_add= '''
  let g:vimfiler_as_default_explorer = 1
	" 別ウィンドウで開く
	nnoremap <space>fe :VimFilerExplore -split -winwidth=30 -find -no-quit<Cr>
	" 現在のファイルのディレクトリで開く
	nnoremap <space>ff :VimFilerCurrentDir<Cr>
	" プロジェクトホームで開く
	nnoremap <space>fg :VimFiler -project<Cr>
'''
# ファイルをtree表示してくれる
# [[plugins]]
# repo = 'scrooloose/nerdtree'

# toml
[[plugins]]
repo = 'cespare/vim-toml'

# Gitを便利に使う
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''

'''

# 静的解析
[[plugins]]
repo = 'scrooloose/syntastic'

# ドキュメント参照
[[plugins]]
repo = 'thinca/vim-ref'
[[plugins]]
repo = 'yuku-t/vim-ref-ri'

# メソッドの定義元へジャンプ
[[plugins]]
repo = 'szw/vim-tags'
# open ctag in tab/vertical split
# map <C-\> :tab split<CR>:exec(#tag #.expand(#<cword>#))<CR>
# map <leader><C-\> :vsp <CR>:exec(#tag #.expand(#<cword>#))<CR>


# コメントON/OFFを手軽に実行
[[plugins]]
repo = 'tomtom/tcomment_vim'
# シングルクオートとダブルクオートの入れ替え等
[[plugins]]
repo = 'tpope/vim-surround'
# インデントに色を付けて見やすくする
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
# ログファイルを色づけしてくれる
[[plugins]]
repo = 'vim-scripts/AnsiEsc.vim'
# 行末の半角スペースを可視化(うまく動かない？)
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# Markdown用
# 参考:http://www.key-p.com/blog/staff/archives/9032
# :PrevimOpen ブラウザでプレビューを表示する
[[plugins]]
repo = 'plasticboy/vim-markdown'
hook_add= '''
  let g:vim_markdown_folding_disabled = 1
'''
[[plugins]]
repo = 'kannokanno/previm'

# [Vim \- URL からブラウザオープン！ \- mk\-mode BLOG](http://www.mk-mode.com/octopress/2014/11/13/vim-open-browser-plugin/)
# gx でカーソル下のURLをブラウザでOPENする
[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
  let g:netrw_nogx = 1 " disable netrw's gx mapping.
  nmap gx <Plug>(openbrowser-smart-search)
  vmap gx <Plug>(openbrowser-smart-search)
'''

# 色々なカラースキーム
# [[plugins]]
# repo = 'flazz/vim-colorschemes'
# hook_add = '''
#   " [dein\.vimによるプラグイン管理のマイベストプラクティス \- Qiita](http://qiita.com/kawaz/items/ee725f6214f91337b42b)
#   " set background=dark
#   " au MyAutoGrp VimEnter * nested colorscheme monokai
# '''

# サブモードを作る
[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'nsf/gocode'
rtp = 'vim'
